clear
clear mtk
summary = runtests({'AlgebraicTest', ...
                    'AlphabeticNameTest', ...
                    'CollinsGisinTest', ...
                    'CompleteTest', ...
                    'GenerateBasisTest', ...               
                    'MomentMatrixTest', ...
                    'NewMatrixSystemTest', ...
                    'VersionTest'});
disp(summary);