clear
clear npatk
summary = runtests({'AlgebraicTest', ...
                    'AlphabeticNameTest', ...
                    'CollinsGisinTest', ...
                    'CompleteTest', ...
                    'GenerateBasisTest', ...
                    'MakeHermitianTest', ...
                    'MakeSymmetricTest', ...                    
                    'MomentMatrixTest', ...
                    'NewMatrixSystemTest', ...
                    'VersionTest'});
disp(summary);