summary = runtests({'AlphabeticNameTest', ...
                    'GenerateBasisTest', ...
                    'MakeHermitianTest', ...
                    'MakeSymmetricTest', ...
                    'MakeMomentMatrixTest', ...
                    'VersionTest'});
disp(summary);